Repository ONEARMY/community-platform, pull requests merged in 2019-10, with the labels that each got.

#606 Fix invalid package name during "npm i"
  package.json
Labels: In progress

#614 Update filters on map #607
  src/assets/icons/icon-checkmark.svg
  src/assets/icons/icon-search.svg
  src/assets/icons/map-cluster-collection.svg
  src/assets/icons/map-cluster-workspace.svg
  src/assets/icons/map-collection.svg
  src/assets/icons/map-community.svg
  src/assets/icons/map-icon-workspace.svg
  src/assets/icons/map-machine.svg
  src/assets/icons/map-member.svg
  src/assets/icons/map-workspace.svg
  src/components/ElWithBeforeIcon/index.tsx
  src/components/LocationSearch/LocationSearch.tsx
  src/mocks/maps.mock.tsx
  src/models/maps.models.tsx
  src/pages/Maps/Content/Controls/GroupingFilter.css
  src/pages/Maps/Content/Controls/GroupingFilter.tsx
  src/pages/Maps/Content/Controls/index.tsx
  src/pages/Maps/Content/View/Cluster.tsx
  src/pages/Maps/Content/View/Popup.tsx
  src/pages/Maps/Content/View/Sprites.tsx
  src/pages/Maps/Content/View/index.tsx
  src/pages/Maps/Content/View/sprites.css
  src/pages/Maps/Maps.tsx
  src/stores/Maps/maps.store.ts
  src/stores/common/module.store.ts
Labels: In progress

#666 Fixes #628: Updated user menu modal
  src/components/ProfileModal/ProfileModal.tsx
  src/pages/common/Header/Profile/Profile.tsx
Labels: Review: Assigned

#667 Fixes #629: add a Safari-compatible datepicker
  package.json
  src/pages/Events/Content/EventsCreate/EventsCreate.css
  src/pages/Events/Content/EventsCreate/EventsCreate.tsx
  yarn.lock
Labels: Review: Assigned

#668 Fixes #620: changed navbar button colors to match the mock-up
  src/pages/common/Login/Login.tsx
  src/themes/styled.theme.tsx
Labels: Review: Assigned

#670 Fixes #615: hide event tags with zero results
  src/components/Tags/TagsSelect.tsx
  src/pages/Events/Content/EventsList/EventsList.tsx
  src/pages/Howto/Content/HowtoList/HowtoList.tsx
Labels: Review: Changes Requested

#682 Fix/646 how to button disable on save and edit test
  cypress/integration/bugs.spec.ts
  cypress/integration/howto/write.spec.ts
  src/pages/Howto/Content/Common/Howto.form.tsx
  src/pages/Howto/Content/Common/SubmitStatus.tsx
  src/pages/Howto/Content/CreateHowto/CreateHowto.tsx
  src/pages/Howto/Content/EditHowto/EditHowto.tsx
  src/stores/Howto/howto.store.tsx
Labels: Review: Assigned 👉

#712 Fixes #678: close dropdown on click away in events
  src/components/LocationSearch/LocationSearch.tsx
Labels: Review: Assigned 👉

#715 Fixes #687: Add close button to location search
  src/components/LocationSearch/LocationSearch.tsx
  src/themes/app.globalStyle.js
Labels: Review: Assigned 👉

#716 Feat/admin section
  package.json
  src/models/user.models.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/content/AdminTags.tsx
  src/pages/admin/content/AdminUsers.tsx
  src/stores/Admin/admin.store.ts
  src/stores/Tags/tags.store.tsx
  src/stores/databaseV2/index.tsx
  src/stores/databaseV2/types/index.d.ts
  src/stores/index.tsx
  src/utils/helpers.ts
  yarn.lock
Labels: Review: Assigned 👉
