Repository ONEARMY/community-platform, pull requests merged in 2022-07, with the labels that each got.

#1805 feat: improve appearance when shared sociallly and when viewed in search engine result pages
  firebase.json
  functions/jest.config.ts
  functions/package.json
  functions/scripts/set-up-environment-variables.ts
  functions/scripts/setupRuntimeConfig.ts
  functions/src/config/config.ts
  functions/src/seo/index.ts
  functions/src/seo/render/render.spec.ts
  functions/src/seo/render/request-handler.ts
  functions/src/seo/sitemap/sitemap.test.ts
  functions/src/seo/sitemap/sitemapGenerate.ts
  functions/src/seo/sitemap/sitemapProxy.ts
  functions/webpack.config.ts
  yarn.lock
Labels: Backend

#1823 fix: seo sitemap how-to typo
  functions/src/seo/sitemap/sitemapGenerate.ts
Labels: Backend

#1826 Chore/seo render tidying
  .firebaserc
  functions/src/seo/index.ts
  functions/src/seo/render/request-handler.ts
Labels: Backend

#1827 feat: add seo tags for research items
  src/models/research.models.tsx
  src/pages/Research/Content/ResearchArticle.tsx
  src/stores/Research/research.store.tsx
Labels: Review allow-preview ✅, Mod: Research 🔬

#1830 fix: lint format seorender function
  functions/src/seo/index.ts
Labels: Backend

#1820 docs: update troubleshooting permissions
  packages/documentation/docs/Install.md
Labels: Documentation

#1824 chore: migrated loader to packages
  packages/components/src/Loader/Loader.stories.tsx
  packages/components/src/Loader/Loader.tsx
  packages/components/src/index.ts
  src/components/FirebaseFileUploader/FirebaseFileUploader.tsx
  src/components/Loader/index.tsx
  src/pages/Howto/Content/EditHowto/EditHowto.tsx
  src/pages/Howto/Content/Howto/Howto.tsx
  src/pages/Howto/Content/HowtoList/HowtoList.tsx
  src/pages/Research/Content/CreateUpdate/index.tsx
  src/pages/Research/Content/EditResearch/index.tsx
  src/pages/Research/Content/EditUpdate/index.tsx
  src/pages/Research/Content/ResearchArticle.tsx
  src/pages/User/content/index.tsx
  src/themes/fixing-fashion/styles.ts
  src/themes/precious-plastic/styles.ts
  src/themes/project-kamp/styles.ts
  src/themes/types.tsx
Labels: Mod: HowTo 📰, Review allow-preview ✅, Mod: Research 🔬
