Repository ONEARMY/community-platform, pull requests merged in 2022-11, with the labels that each got.

#1987 Feat/admin users
  packages/components/src/Icon/Icon.tsx
  packages/components/src/Icon/types.ts
  src/assets/images/badges/pt-collection-point.jpg
  src/assets/images/badges/pt-local-community.jpg
  src/assets/images/badges/pt-machine-shop.jpg
  src/assets/images/badges/pt-member.jpg
  src/assets/images/badges/pt-workspace.jpg
  src/mocks/Selectors.tsx
  src/models/user.models.tsx
  src/modules/admin/admin.routes.tsx
  src/modules/admin/components/Table/HeadFilter.tsx
  src/modules/admin/components/Table/Table.tsx
  src/modules/admin/components/Table/TableHead.tsx
  src/modules/admin/components/adminUserSearch.tsx
  src/modules/admin/pages/adminUsers.tsx
  src/pages/Settings/content/formSections/UserInfos.section.tsx
Labels: Backend

#1998 Chore: Update emulators to use latest pp data
  .github/workflows/docker-emulator-build.yml
  functions/jest.config.ts
  functions/package.json
  functions/scripts/set-up-environment-variables.ts
  functions/src/Firebase/admin.ts
  functions/src/Firebase/auth.ts
  functions/src/Firebase/firebaseSync.ts
  functions/src/Firebase/firestoreDB.ts
  functions/src/Firebase/firestoreDBExport.ts
  functions/src/Firebase/realtimeDB.spec.ts
  functions/src/Firebase/realtimeDB.ts
  functions/src/Firebase/storage.ts
  functions/src/admin/getUserEmail.ts
  functions/src/aggregations/common.aggregations.ts
  functions/src/emulator/seed/data-clean.ts
  functions/src/emulator/seed/users-create.ts
  functions/src/seo/render/render.spec.ts
  functions/src/userUpdates/index.test.ts
  packages/emulators-docker/.gitignore
  packages/emulators-docker/Dockerfile
  packages/emulators-docker/seed_data/pp-2022-06-28.tar.gz
  packages/emulators-docker/seed_data/pp-2022-10-30.tar.gz
  packages/emulators-docker/src/build.ts
  packages/emulators-docker/src/common.ts
  packages/emulators-docker/src/prepare.ts
  packages/emulators-docker/src/start.ts
  yarn.lock
Labels: Backend

#2000 fix: pin firebase-functions to older version
  .github/workflows/docker-emulator-build.yml
  functions/package.json
  yarn.lock
Labels: Backend

#1995 fix: keep filters in sync with url after back/forward navigation on how-to page
  packages/cypress/src/integration/howto/search.spec.ts
  src/pages/Howto/Category/CategoriesSelect.tsx
  src/pages/Howto/Content/HowtoList/HowtoList.tsx
  src/pages/Howto/VirtualizedFlex/VirtualizedFlex.tsx
Labels: Mod: HowTo 📰, Review allow-preview ✅, Design Approved, Bounty Level 2

#2003 fix: member icons for settings and profile
  src/modules/profile/SupportedProfileTypesFactory.ts
  src/modules/profile/index.ts
  src/pages/User/content/MemberProfile.tsx
  src/themes/fixing-fashion/styles.ts
  src/themes/precious-plastic/styles.ts
  src/themes/project-kamp/styles.ts
Labels: Review allow-preview ✅

#2004 fix: research update, do not show identical created/edited timestamps
  src/pages/Research/Content/ResearchUpdate.test.tsx
  src/pages/Research/Content/ResearchUpdate.tsx
Labels: Review allow-preview ✅, Mod: Research 🔬

#2005 fix: how-to virtualized grid
  src/pages/Howto/Content/HowtoList/HowToCard.tsx
  src/pages/Howto/Content/HowtoList/HowtoList.tsx
  src/pages/Howto/VirtualizedFlex/VirtualizedFlex.tsx
Labels: Mod: HowTo 📰, Review allow-preview ✅
