Repository ONEARMY/community-platform, pull requests merged in 2022-08, with the labels that each got.

#1857 fix: location icon color fix
  src/pages/User/content/UserStats.tsx
Labels: Review allow-preview ✅

#1817 chore: migrate ImageGallery to packages
  packages/components/src/ImageGallery/ImageGallery.stories.tsx
  packages/components/src/ImageGallery/ImageGallery.tsx
  packages/components/src/index.ts
  src/components/ImageGallery/ImageGallery.tsx
  src/pages/Howto/Content/Howto/Step/Step.tsx
  src/pages/Research/Content/ResearchUpdate.tsx
Labels: Mod: HowTo 📰, Mod: Research 🔬

#1858 fix: removed external links from mobile menu.
  src/pages/common/Header/Menu/MenuMobile/MenuMobilePanel.tsx
Labels: Review allow-preview ✅

#1859 fix: reduced how-to heading padding for mobile
  src/pages/Howto/Content/HowtoList/HowtoList.tsx
Labels: Mod: HowTo 📰, Review allow-preview ✅

#1868 fix: change button on sign up message page
  src/pages/SignUp/SignUpMessage.tsx
Labels: Review allow-preview ✅, Design Approved

#1869 fix: add visibility to SelectField child items when exceeding parent
  src/pages/Settings/content/formSections/elements.tsx
Labels: Review allow-preview ✅

#1865 fix(functions): updating user info in howto comments
  functions/src/userUpdates/index.ts
Labels: Backend, Review allow-preview ✅

#1882 fix: contacts & links layout
  src/pages/Settings/content/formSections/Fields/Link.field.tsx
Labels: Review allow-preview ✅, Design Approved

#1879 feat: remove map zoom control on mobile/tablet
  src/pages/Maps/Content/View/index.tsx
Labels: Mod: Maps 🗺, Review allow-preview ✅, Design Approved

#1880 fix: removed brackets
  src/pages/Settings/content/ProfileDelete.tsx
Labels: Review allow-preview ✅

#1876 fix: fix alignment of reset email sent message
  src/pages/SignIn/SignIn.tsx
Labels: Review allow-preview ✅, Design Approved

#1878 fix: fix alignment of sign-up checkbox
  src/pages/SignUp/SignUp.tsx
Labels: Review allow-preview ✅, Design Approved

#1855 fix: flex layout for mobiles
  packages/components/src/ImageGallery/ImageGallery.tsx
  src/pages/Howto/Content/Howto/Step/Step.tsx
Labels: Mod: HowTo 📰, Review allow-preview ✅, Design Approved, 🤝 Awaiting author

#1886 fix: activity grid within settings
  src/pages/Settings/content/formSections/Fields/CustomRadio.field.tsx
  src/pages/Settings/content/formSections/Focus.section.tsx
Labels: Design, Review allow-preview ✅, Design Approved

#1885 fix: settings height for mobile devices
  src/pages/Settings/SettingsPage.tsx
Labels: Review allow-preview ✅, Design Approved

#1891 Fixes link styles for research and how-to articles
  src/components/StyledLinkify/StyledLinkify.tsx
  src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
  src/pages/Howto/Content/Howto/Step/Step.tsx
  src/pages/Research/Content/ResearchDescription.tsx
  src/pages/Research/Content/ResearchUpdate.tsx
Labels: Mod: HowTo 📰, Review allow-preview ✅, Mod: Research 🔬, Design Approved

#1902 fix: user menu items
  src/pages/common/Header/Menu/ProfileModal/ProfileModal.tsx
Labels: Review allow-preview ✅, Design Approved

#1892 fix: added flex to container to prevent overflow of content
  src/pages/User/content/SpaceProfile.tsx
Labels: 🤝 Awaiting author
