Repository ONEARMY/community-platform, pull requests merged in 2023-06, with the labels that each got.

#2398 fix: use icon only variant
  src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
Labels: Mod: HowTo 📰

#2404 feat: adds logging backend method
  functions/package.json
  functions/src/index.ts
  functions/src/logging/logging.spec.ts
  functions/src/logging/logging.ts
  yarn.lock
Labels: Backend

#2411 refactor: remove direct usage of theme from header component
  src/pages/common/Header/Header.tsx
Labels: Review allow-preview ✅

#2414 docs: update outline of deployment steps
  packages/documentation/docs/Contributing/start-contributing.md
Labels: Documentation

#2344 feat: migrate useful voting, add new useful aggregation & fix useful counts
  functions/src/aggregations/common.aggregations.ts
  functions/src/aggregations/howto.aggregations.ts
  functions/src/aggregations/index.ts
  functions/src/aggregations/migrations.ts
  functions/src/aggregations/research.aggregations.ts
  functions/src/aggregations/user.aggregations.ts
  functions/src/stats/index.ts
  packages/components/src/UsefulStatsButton/UsefulStatsButton.tsx
  src/common/hooks/userStats.ts
  src/common/hooks/userUsefulCount.ts
  src/models/common.models.tsx
  src/models/howto.models.tsx
  src/models/research.models.tsx
  src/models/user.models.tsx
  src/modules/admin/admin.routes.tsx
  src/modules/admin/pages/adminDatabase.tsx
  src/modules/admin/pages/adminNotifications.tsx
  src/pages/Howto/Content/Howto/Howto.test.tsx
  src/pages/Howto/Content/Howto/Howto.tsx
  src/pages/Howto/Content/HowtoList/HowtoList.tsx
  src/pages/Howto/Howto.tsx
  src/pages/Research/Content/ResearchArticle.test.tsx
  src/pages/Research/Content/ResearchArticle.tsx
  src/pages/Research/Content/ResearchDescription.tsx
  src/pages/Research/Content/ResearchList.tsx
  src/pages/Research/Content/ResearchListItem.tsx
  src/pages/Research/index.tsx
  src/pages/Settings/UserSettings.test.tsx
  src/pages/User/content/MemberProfile.tsx
  src/pages/User/content/SpaceProfile.tsx
  src/pages/User/content/index.tsx
  src/stores/Aggregations/aggregations.store.tsx
  src/stores/Howto/howto.store.tsx
  src/stores/Research/research.store.tsx
  src/stores/User/user.store.ts
  src/stores/databaseV2/DocReference.tsx
  src/stores/databaseV2/clients/dexie.tsx
  src/stores/databaseV2/clients/firestore.tsx
  src/stores/databaseV2/clients/rtdb.tsx
  src/stores/databaseV2/types/AbstractDatabaseClient.ts
  src/stores/databaseV2/types/index.d.ts
Labels: Backend, Mod: HowTo 📰, Review allow-preview ✅, Mod: Research 🔬

#2421 fix: collaborator useful aggregation
  functions/src/aggregations/common.aggregations.ts
  functions/src/aggregations/research.aggregations.ts
Labels: Backend

#2423 refactor/fix: useful aggregation seed improvements & db update metadata overwrite
  functions/src/aggregations/common.aggregations.ts
  src/stores/databaseV2/DocReference.tsx
Labels: Backend

#2425 fix: useful aggregation seed update entry generation
  functions/src/aggregations/common.aggregations.ts
  src/stores/databaseV2/DocReference.tsx
Labels: Backend

#2429 fix: nesting of anchor links
  packages/cypress/src/integration/howto/read.spec.ts
  src/pages/Howto/Content/HowtoList/HowToCard.tsx
Labels: Mod: HowTo 📰

#2431 fix: notify event accepted discord hook error
  functions/src/Integrations/firebase-discord.ts
Labels: Backend

#2432 fix: update useful aggregation to only count useful from accepted docs
  functions/src/aggregations/common.aggregations.ts
  functions/src/aggregations/howto.aggregations.ts
  functions/src/aggregations/research.aggregations.ts
Labels: Backend

#2405 fix(emails): use userName in links
  functions/src/emailNotifications/createEmail.spec.ts
  functions/src/emailNotifications/createEmail.ts
  functions/src/emailNotifications/pk-template.handlebars
  functions/src/emailNotifications/pp-template.handlebars
Labels: Backend

#2430 feat: add contributors to research description
  src/pages/Research/Content/ResearchArticle.test.tsx
  src/pages/Research/Content/ResearchArticle.tsx
  src/pages/Research/Content/ResearchDescription.tsx
Labels: Review allow-preview ✅, Mod: Research 🔬

#2428 feat: show user howto & research on member / space profile
  functions/src/index.ts
  functions/src/stats/index.ts
  src/common/hooks/userStats.ts
  src/pages/User/content/MemberProfile.tsx
  src/pages/User/content/SpaceProfile.tsx
  src/pages/User/content/UserCreatedDocuments.tsx
  src/pages/User/content/UserCreatedDocumentsItem.tsx
  src/pages/User/content/index.tsx
  src/stores/User/user.store.ts
  src/stores/databaseV2/clients/dexie.tsx
Labels: Backend, Review allow-preview ✅

#2456 fix: typo in start.ts
  functions/scripts/start.ts
Labels: Backend

#2454 feature: research page card redesign
  packages/components/assets/icons/icon-update.svg
  packages/components/src/Icon/Icon.tsx
  packages/components/src/Icon/svgs.tsx
  packages/components/src/Icon/types.ts
  src/pages/Research/Content/ResearchList.tsx
  src/pages/Research/Content/ResearchListItem.tsx
Labels: Review allow-preview ✅, Mod: Research 🔬

#2453 fix: how-to most useful sort
  src/pages/Howto/Content/HowtoList/HowToCard.tsx
  src/pages/Howto/Content/HowtoList/HowtoList.tsx
  src/pages/Howto/Content/HowtoList/SortSelect.tsx
  src/stores/Howto/howto.store.test.ts
  src/stores/Howto/howto.store.tsx
  src/test/factories/Howto.ts
Labels: Mod: HowTo 📰

#2461 chore: font size fixed and cleaned the unnecessary comments
  src/pages/Research/Content/ResearchListItem.tsx
  src/pages/common/Header/Menu/Profile/ProfileButtons.tsx
Labels: Mod: Research 🔬

#2462 [refactor] Remove direct usage of Theme
  src/modules/admin/pages/adminApprovals.tsx
  src/pages/Events/Content/EventsCreate/EventsCreate.tsx
  src/pages/Howto/Content/Common/Howto.form.tsx
  src/pages/Howto/Content/Common/HowtoStep.form.tsx
  src/pages/Settings/SettingsPage.tsx
  src/pages/Settings/content/formSections/MemberMapPin.section.tsx
  src/pages/Settings/content/formSections/UserInfos.section.tsx
  src/pages/Settings/content/formSections/WorkspaceMapPin.section.tsx
  src/pages/common/Layout/Main.tsx
Labels: Mod: HowTo 📰, Mod: Events 🎉, Review allow-preview ✅

#2476 feat: add show hide password icon
  packages/components/assets/icons/eye-crossed.svg
  packages/components/assets/icons/eye.svg
  packages/components/src/Icon/Icon.tsx
  packages/components/src/Icon/svgs.tsx
  packages/components/src/Icon/types.ts
  src/common/Form/PasswordField.tsx
  src/pages/Settings/content/formSections/ChangeEmail.form.tsx
  src/pages/Settings/content/formSections/ChangePassword.form.tsx
  src/pages/SignIn/SignIn.tsx
  src/pages/SignUp/SignUp.tsx
Labels: Review allow-preview ✅

#2482 chore: remove user stats functions
  functions/src/index.ts
  functions/src/stats/index.ts
  functions/src/stats/migration.ts
Labels: Backend

#2484 feat: change the style of delete buttons
  src/pages/Settings/content/ProfileDelete.tsx
  src/pages/Settings/content/formSections/AccountSettings.section.tsx
Labels: Review allow-preview ✅

#2492 chore: remove unused component documentation
  src/pages/Events/EventCard/event.card.stories.mdx
  src/pages/User/content/MemberProfile.stories.mdx
  src/pages/User/content/SpaceProfile.stories.mdx
Labels: Mod: Events 🎉

#2495 fix: remove last active from map pin
  packages/components/src/MapMemberCard/MapMemberCard.stories.tsx
  packages/components/src/MapMemberCard/MapMemberCard.tsx
  src/models/maps.models.tsx
  src/pages/Maps/Content/View/Popup.tsx
  src/stores/Maps/generatePins.tsx
  src/stores/Maps/maps.store.ts
Labels: Mod: Maps 🗺, Review: Changes Requested 🗨️

#2196 feat(components): new VideoPlayer, supports Vimeo/Youtube and more
  package.json
  packages/components/package.json
  packages/components/src/VideoPlayer/VideoPlayer.stories.tsx
  packages/components/src/VideoPlayer/VideoPlayer.test.tsx
  packages/components/src/VideoPlayer/VideoPlayer.tsx
  packages/components/src/index.ts
  packages/cypress/src/integration/howto/read.spec.ts
  src/pages/Howto/Content/Howto/Step/Step.tsx
  src/pages/Research/Content/ResearchUpdate.tsx
  yarn.lock
Labels: Mod: HowTo 📰, Mod: Research 🔬
