Repository ONEARMY/community-platform, pull requests merged in 2023-12, with the labels that each got.

#3032 fix: removed unnecessary padding in Questions page
  src/pages/Question/QuestionCreate.tsx
  src/pages/Question/QuestionEdit.tsx
  src/pages/Question/QuestionListing.tsx
Labels: Review allow-preview ✅

#3043 feat(question): select tags
  src/models/question.models.tsx
  src/models/tags.model.tsx
  src/pages/Question/Content/Common/QuestionForm.tsx
  src/pages/Question/QuestionCreate.tsx
  src/pages/Question/QuestionEdit.tsx
  src/pages/Question/labels.ts
  src/pages/Question/question.routes.test.tsx
  src/stores/Tags/tags.store.tsx
Labels: Review allow-preview ✅

#3042 feat(question): add mark-as-useful button
  src/pages/Question/QuestionPage.tsx
  src/stores/Question/question.store.tsx
Labels: Review allow-preview ✅

#3006 feat: support image CDN across site
  packages/components/src/ImageGallery/ImageGallery.stories.tsx
  packages/components/src/ImageGallery/ImageGallery.test.tsx
  packages/components/src/ImageGallery/ImageGallery.tsx
  packages/components/src/index.ts
  src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
  src/pages/Howto/Content/Howto/Step/Step.tsx
  src/pages/Howto/Content/HowtoList/HowToCard.tsx
  src/pages/Research/Content/ResearchListItem.tsx
  src/pages/Research/Content/ResearchUpdate.tsx
  src/pages/User/content/SpaceProfile.tsx
  src/utils/cdnImageUrl.test.ts
  src/utils/cdnImageUrl.ts
  src/utils/formatImageListForGallery.ts
Labels: Mod: HowTo 📰, Mod: Research 🔬

#3039 [Snyk] Security upgrade @google-cloud/logging from 10.5.0 to 11.0.0
  functions/package.json
  yarn.lock
Labels: Backend

#3016 feat(patreon): set up auth with patreon
  .circleci/config.yml
  firestore.rules
  functions/scripts/runtimeConfig/model.ts
  functions/src/Integrations/index.ts
  functions/src/Integrations/patreon.ts
  functions/src/config/config.ts
  packages/documentation/docs/Backend Development/integrations.md
  packages/security-rules/tests/general.spec.ts
  shared/models/db.ts
  src/config/config.ts
  src/config/constants.ts
  src/models/user.models.tsx
  src/pages/PageList.tsx
  src/pages/Patreon/Patreon.tsx
  src/pages/UserSettings/SettingsPage.tsx
  src/stores/databaseV2/clients/dexie.tsx
Labels: Documentation, Backend, Review allow-preview ✅

#3059 fix: doc link to public figma file
  packages/documentation/docs/Design/our-design-system.md
Labels: Documentation

#3027 feat: update tab styling
  packages/components/src/TabbedContent/TabbedContent.tsx
  src/pages/User/contact/UserContactFieldEmail.tsx
  src/pages/User/contact/UserContactFieldMessage.tsx
  src/pages/User/contact/UserContactFieldName.tsx
  src/pages/User/impact/ImpactField.tsx
  src/pages/User/impact/ImpactItem.tsx
Labels: Review allow-preview ✅

#3064 fix(patreon): lookup by auth id
  functions/src/Integrations/patreon.ts
Labels: Backend

#3065 fix(patreon): increase memory limits
  functions/src/Integrations/patreon.ts
  functions/src/consts.ts
  functions/src/emailNotifications/createModerationEmails.ts
  functions/src/emailNotifications/index.ts
  functions/src/emailNotifications/utils.ts
Labels: Backend

#3035 feat(patreon): build frontend integration
  functions/src/Integrations/patreon.ts
  shared/models/user.ts
  src/models/user.models.tsx
  src/pages/Patreon/Patreon.tsx
  src/pages/UserSettings/SettingsPage.tsx
  src/pages/UserSettings/content/formSections/PatreonIntegration.tsx
Labels: Backend, Review allow-preview ✅

#3044 fix: select component highlights focused element on keyboard navigation
  packages/components/src/Select/Select.tsx
Labels: Review allow-preview ✅

#3052 feat(question): create draft
  src/models/question.models.tsx
  src/pages/Question/Content/Common/QuestionForm.tsx
  src/pages/Question/QuestionListing.tsx
  src/pages/Question/QuestionPage.tsx
  src/pages/Question/labels.ts
  src/pages/Question/question.routes.test.tsx
  src/stores/Question/question.store.test.tsx
  src/stores/Question/question.store.tsx
Labels: Review allow-preview ✅

#3053 feat(question): add username and Ask-On date
  functions/src/userUpdates/index.ts
  src/models/question.models.tsx
  src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
  src/pages/Question/QuestionPage.tsx
  src/pages/Research/Content/ResearchDescription.tsx
  src/pages/common/UserNameTag/UserNameTag.tsx
  src/stores/Question/question.store.tsx
Labels: Backend, Mod: HowTo 📰, Review allow-preview ✅, Mod: Research 🔬

#3071 Update messages on impact data display
  src/models/user.models.tsx
  src/pages/User/impact/Impact.test.tsx
  src/pages/User/impact/Impact.tsx
  src/pages/User/impact/ImpactItem.tsx
  src/pages/User/impact/ImpactMissing.tsx
  src/pages/User/impact/constants.ts
  src/pages/User/impact/labels.ts
Labels: Review allow-preview ✅, 🤝 Awaiting author

#3049 feat: update message templates for consistency
  functions/src/emailNotifications/createSubmissionEmails.ts
  functions/src/emailNotifications/templates.ts
  functions/src/emailNotifications/templates/receiver-message.html
  functions/src/emailNotifications/templates/sender-message.html
Labels: Backend, 🤝 Awaiting author

#3040 feat(question): select category
  shared/models/db.ts
  src/models/question.models.tsx
  src/models/questionCategories.model.ts
  src/pages/Howto/Category/CategoriesSelect.tsx
  src/pages/Question/Content/Common/QuestionForm.tsx
  src/pages/Question/question.routes.test.tsx
  src/stores/QuestionCategories/questionCategories.store.tsx
  src/stores/databaseV2/clients/dexie.tsx
  src/stores/index.tsx
Labels: Mod: HowTo 📰, Review allow-preview ✅, 🤝 Awaiting author

#3078 feat(patreon): link to supporter badge and update integration module
  functions/src/Integrations/patreon.spec.ts
  functions/src/Integrations/patreon.ts
  src/models/user.models.tsx
  src/pages/UserSettings/SettingsPage.tsx
  src/pages/UserSettings/content/formSections/PatreonIntegration.test.tsx
  src/pages/UserSettings/content/formSections/PatreonIntegration.tsx
  src/stores/User/user.store.ts
Labels: Backend, Review allow-preview ✅

#3086 feat(questions): display update date on questions and share component
  packages/cypress/src/integration/howto/read.spec.ts
  src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
  src/pages/Question/QuestionPage.tsx
  src/pages/Research/Content/ResearchDescription.tsx
  src/pages/common/ContentAuthorTimestamp/ContentAuthorTimestamp.tsx
Labels: Mod: HowTo 📰, Mod: Research 🔬, 🤝 Awaiting author

#3097 refactor: removed unused file upload components
  package.json
  src/pages/Howto/Content/Common/Howto.form.tsx
  src/pages/common/UploadedFile/FirebaseFileUploader.tsx
  src/pages/common/UploadedFile/ImagePreview.tsx
  src/pages/common/UploadedFile/UploadedFile.scss
  src/pages/common/UploadedFile/UploadedFile.tsx
  types/react-firebase-file-uploader.d.ts
  types/react-firebase-file-uploader/index.d.ts
  yarn.lock
Labels: Mod: HowTo 📰, 🤝 Awaiting author

#3106 test: refactor to match React naming conventions
  src/pages/Howto/Content/Common/Howto.form.test.tsx
  src/pages/Maps/Maps.test.tsx
  src/pages/UserSettings/UserSettings.test.tsx
Labels: Mod: HowTo 📰, Mod: Maps 🗺

#3108 chore: refactor remove use of hooks in ModuleStore class
  src/pages/Question/index.tsx
  src/pages/Research/index.tsx
  src/stores/common/module.store.ts
Labels: Mod: Research 🔬

#3119 refactor: remaining class components to hooks
  packages/components/src/ModerationStatus/ModerationStatus.tsx
  src/App.tsx
  src/pages/Howto/Content/Common/Howto.form.tsx
  src/pages/Howto/Content/Common/HowtoFieldStep.tsx
  src/pages/Howto/VirtualizedFlex/VirtualizedFlex.tsx
  src/pages/Maps/Content/Controls/GroupingFilterDesktop.tsx
  src/pages/Maps/Content/Controls/GroupingFilterMobile.tsx
  src/pages/Maps/Content/MapView/Popup.tsx
  src/pages/Research/Content/Common/ResearchUpdate.form.test.tsx
Labels: Mod: HowTo 📰, Mod: Maps 🗺, Mod: Research 🔬
