Repository ONEARMY/community-platform, pull requests merged in 2023-11, with the labels that each got.

#2978 feat: add helper for loading images from CDN
  src/config/config.ts
  src/config/constants.ts
  src/pages/Howto/Content/HowtoList/HowToCard.tsx
  src/utils/cdnImageUrl.test.ts
  src/utils/cdnImageUrl.ts
Labels: Mod: HowTo 📰, Review allow-preview ✅

#2988 feat: add clickable more information component
  packages/components/src/ContentStatistics/ContentStatistics.tsx
  packages/components/src/Icon/Icon.tsx
  packages/components/src/Icon/types.ts
Labels: Review allow-preview ✅

#2980 fix: Change wording and default filter options in research 2925
  src/pages/common/SortFilterHeader/SortFilterHeader.tsx
  src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
Labels: Review allow-preview ✅

#2975 feat: hide member pins on pp only
  packages/cypress/src/integration/map.spec.ts
  shared/mocks/data/mappins.ts
  src/stores/Maps/maps.store.ts
Labels: Review allow-preview ✅

#2994 fix(emulators): fix functions tests
  .circleci/config.yml
  functions/package.json
  functions/src/admin/getUserEmail.ts
  functions/src/emailNotifications/createModerationEmails.spec.ts
  functions/src/emailNotifications/createSubmissionEmails.spec.ts
  functions/src/emailNotifications/utils.ts
  functions/src/emulator/seed/content-generate.ts
Labels: Backend

#2995 test revert
  .circleci/config.yml
Labels: Documentation, Backend

#2996 fix: focus alignment
  src/pages/UserSettings/content/formSections/Fields/CustomRadio.field.tsx
  src/pages/UserSettings/content/formSections/Focus.section.tsx
Labels: Review allow-preview ✅

#2947 feat: add profile contact form
  functions/src/emailNotifications/createSubmissionEmails.spec.ts
  functions/src/emailNotifications/createSubmissionEmails.ts
  functions/src/emailNotifications/index.ts
  functions/src/emailNotifications/templates.ts
  functions/src/emailNotifications/templates/index.ts
  functions/src/emailNotifications/templates/receiver-message.html
  functions/src/emailNotifications/templates/sender-message.html
  functions/src/emailNotifications/utils.ts
  functions/src/models.ts
  packages/cypress/src/integration/profile.spec.ts
  packages/cypress/src/integration/settings.spec.ts
  shared/mocks/data/users.ts
  shared/models/db.ts
  src/models/index.ts
  src/models/message.models.tsx
  src/models/user.models.tsx
  src/pages/User/constants.ts
  src/pages/User/contact/UserContactError.tsx
  src/pages/User/contact/UserContactFieldEmail.tsx
  src/pages/User/contact/UserContactFieldMessage.tsx
  src/pages/User/contact/UserContactFieldName.tsx
  src/pages/User/contact/UserContactForm.test.tsx
  src/pages/User/contact/UserContactForm.tsx
  src/pages/User/contact/index.ts
  src/pages/User/content/SpaceProfile.tsx
  src/pages/User/labels.ts
  src/pages/UserSettings/SettingsPage.tsx
  src/pages/UserSettings/Template.tsx
  src/pages/UserSettings/constants.ts
  src/pages/UserSettings/content/formSections/PublicContact.section.test.tsx
  src/pages/UserSettings/content/formSections/PublicContact.section.tsx
  src/pages/UserSettings/labels.ts
  src/stores/Message/message.store.tsx
  src/stores/databaseV2/clients/dexie.tsx
  src/stores/index.tsx
  src/test/factories/Message.ts
Labels: Backend, Review allow-preview ✅

#2886 feat: add next prev buttons to image gallery
  package.json
  packages/components/assets/icons/chevron-left.svg
  packages/components/assets/icons/chevron-right.svg
  packages/components/src/Icon/Icon.tsx
  packages/components/src/Icon/svgs.tsx
  packages/components/src/ImageGallery/ImageGallery.stories.tsx
  packages/components/src/ImageGallery/ImageGallery.test.tsx
  packages/components/src/ImageGallery/ImageGallery.tsx
  src/assets/icons/icon-star-default.svg
  src/pages/User/content/SpaceProfile.tsx
  yarn.lock
Labels: Code: Tidying, Backend, Review allow-preview ✅

#2906 feat: adding the ability to click on howto/research stats and redirect to list
  packages/components/src/UserStatistics/UserStatistics.test.tsx
  packages/components/src/UserStatistics/UserStatistics.tsx
  src/pages/common/SortFilterHeader/SortFilterHeader.tsx
Labels: Review allow-preview ✅, 🤝 Awaiting author

#3003 fix: contact message issues
  functions/src/emailNotifications/createSubmissionEmails.ts
  functions/src/emailNotifications/templates.ts
  packages/cypress/src/integration/profile.spec.ts
  src/pages/User/contact/UserContactFieldEmail.tsx
  src/pages/User/contact/UserContactForm.test.tsx
  src/pages/User/contact/UserContactForm.tsx
  src/pages/User/labels.ts
Labels: Backend, Review allow-preview ✅

#2837 fix: prevent header layout shift on login
  src/pages/common/Header/Menu/MenuMobile/MenuMobilePanel.tsx
  src/pages/common/Header/Menu/Notifications/NotificationsDesktop.tsx
  src/pages/common/Header/Menu/Profile/Profile.tsx
  src/pages/common/Header/Menu/Profile/ProfileButtonItem.tsx
  src/pages/common/Header/Menu/Profile/ProfileButtons.tsx
  src/pages/common/Header/Menu/Profile/profile.css
  src/stores/User/user.store.ts
Labels: Review allow-preview ✅

#3013 fix: use consistent theme provider
  packages/components/.storybook/preview.tsx
  packages/components/src/ResearchEditorOverview/__snapshots__/ResearchEditorOverview.test.tsx.snap
  packages/components/src/tests/utils.tsx
  src/App.tsx
  src/pages/Howto/Content/Common/Howto.form.test.tsx
  src/pages/Maps/Maps.test.tsx
  src/pages/Research/Content/Common/ResearchUpdate.form.test.tsx
  src/pages/UserSettings/UserSettings.test.tsx
Labels: Mod: HowTo 📰, Mod: Maps 🗺, Mod: Research 🔬

#3020 chore(patreon): update preview deploy with patreon env variable
  .github/workflows/pr-preview.yml
Labels: Review allow-preview ✅

#3017 feat(question): update sidebar explanation
  src/pages/Question/Content/Common/PostingGuidelines.tsx
  src/pages/Question/Content/Common/index.ts
  src/pages/Question/QuestionCreate.tsx
  src/pages/Question/QuestionEdit.tsx
Labels: Review allow-preview ✅

#3004 feat: add display of impact data
  packages/cypress/src/integration/profile.spec.ts
  shared/mocks/data/users.ts
  src/models/user.models.tsx
  src/pages/User/content/SpaceProfile.tsx
  src/pages/User/impact/Impact.test.tsx
  src/pages/User/impact/Impact.tsx
  src/pages/User/impact/ImpactEmoji.tsx
  src/pages/User/impact/ImpactField.tsx
  src/pages/User/impact/ImpactItem.tsx
  src/pages/User/impact/ImpactMissing.tsx
  src/pages/User/impact/constants.ts
  src/pages/User/impact/labels.ts
  src/utils/helpers.test.ts
  src/utils/helpers.ts
Labels: Review allow-preview ✅

#3000 fix: hide member mappins on precious plastic
  packages/cypress/src/integration/settings.spec.ts
  src/config/config.ts
  src/pages/Maps/Content/Controls/Controls.tsx
  src/pages/Maps/Content/Controls/GroupingFilterDesktop.tsx
  src/pages/Maps/Content/Controls/GroupingFilterMobile.tsx
  src/pages/Maps/Maps.tsx
  src/stores/Maps/maps.store.ts
Labels: Mod: Maps 🗺, Review allow-preview ✅, 🤝 Awaiting author
