Repository ONEARMY/community-platform, pull requests merged in 2024-08, with the labels that each got.

#3814 fix: content updating when userImage changes
  functions/src/userUpdates/hasKeyDetailsChanged.test.ts
  functions/src/userUpdates/hasKeyDetailsChanged.ts
  functions/src/userUpdates/updateDiscussionComments.ts
Labels: Backend

#3780 fix: responsive design of tabs on profile
  packages/components/src/TabbedContent/TabbedContent.stories.tsx
  packages/components/src/TabbedContent/TabbedContent.tsx
Labels: Review allow-preview ✅

#3811 feat(updated settings): refactor user profile
  packages/components/src/Button/Button.tsx
  packages/components/src/FieldInput/FieldInput.tsx
  packages/components/src/ResearchEditorOverview/__snapshots__/ResearchEditorOverview.test.tsx.snap
  packages/components/src/Select/Select.tsx
  packages/components/src/SettingsFormWrapper/SettingsFormTabList.tsx
  packages/components/src/SettingsFormWrapper/SettingsFormWrapper.tsx
  packages/cypress/src/integration/common.spec.ts
  packages/cypress/src/integration/settings.spec.ts
  packages/cypress/src/support/commandsUi.ts
  packages/themes/src/common/button.ts
  packages/themes/src/common/commonStyles.ts
  packages/themes/src/common/index.ts
  src/common/Form/ImageInput/ImageInput.tsx
  src/common/Form/Select.field.tsx
  src/pages/Patreon/Patreon.tsx
  src/pages/UserSettings/SettingsPage.tsx
  src/pages/UserSettings/Template.tsx
  src/pages/UserSettings/content/formSections/AccountSettings.section.tsx
  src/pages/UserSettings/content/formSections/Collection.section.tsx
  src/pages/UserSettings/content/formSections/Expertise.section.tsx
  src/pages/UserSettings/content/formSections/Fields/OpeningHoursPicker.field.tsx
  src/pages/UserSettings/content/formSections/Fields/ProfileLink.field.tsx
  src/pages/UserSettings/content/formSections/Impact/Impact.section.tsx
  src/pages/UserSettings/content/formSections/PatreonIntegration.tsx
  src/pages/UserSettings/content/formSections/PublicContact.section.tsx
  src/pages/UserSettings/content/formSections/SettingsMapPin.section.tsx
  src/pages/UserSettings/content/formSections/SettingsNotifications.section.tsx
  src/pages/UserSettings/content/formSections/UserImages.section.tsx
  src/pages/UserSettings/content/formSections/UserInfos.section.tsx
  src/pages/UserSettings/content/formSections/UserProfile.section.tsx
  src/pages/UserSettings/content/formSections/UserProfile.test.tsx
  src/pages/UserSettings/content/formSections/Workspace.section.tsx
  src/pages/UserSettings/content/formSections/elements.tsx
  src/pages/UserSettings/labels.ts
  src/stores/User/user.store.test.tsx
  src/stores/User/user.store.ts
Labels: Review allow-preview ✅

#3816 fix: improve comments performance
  packages/components/src/CreateComment/CreateComment.tsx
  packages/components/src/DiscussionContainer/DiscussionContainer.stories.tsx
  packages/components/src/DiscussionContainer/DiscussionContainer.tsx
  src/common/DiscussionWrapper.tsx
  src/common/HideDiscussionContainer.tsx
  src/stores/Discussions/discussionEvents.ts
  src/stores/Discussions/discussions.store.tsx
Labels: Review allow-preview ✅

#3823 feat(research): changed max length of research description from 1000 to 3000
  src/pages/Research/constants.ts
Labels: Review allow-preview ✅, Mod: Research 🔬, Design Approved

#3830 fix: email link to PK header image
  functions/src/emailNotifications/constants.ts
Labels: Backend

#3834 fix: saving a research article as a draft does not trigger webhook
  functions/src/Integrations/firebase-discord.test.ts
  functions/src/Integrations/firebase-discord.ts
Labels: Backend
