Repository ONEARMY/community-platform, pull requests merged in 2024-02, with the labels that each got.

#3244 fix: hide prev and next buttons when there is only one image in the p…
  packages/components/src/ImageGallery/ImageGallery.stories.tsx
  packages/components/src/ImageGallery/ImageGallery.test.tsx
  packages/components/src/ImageGallery/ImageGallery.tsx
Labels: Review allow-preview ✅, 🤝 Awaiting author

#3225 feat: support replies
  packages/components/src/CommentItem/CommentItem.tsx
  packages/components/src/CommentList/CommentList.stories.tsx
  packages/components/src/CommentList/CommentList.test.tsx
  packages/components/src/CommentList/CommentList.tsx
  packages/components/src/CreateComment/CreateComment.tsx
  packages/components/src/DiscussionContainer/DiscussionContainer.stories.tsx
  packages/components/src/DiscussionContainer/DiscussionContainer.test.tsx
  packages/components/src/DiscussionContainer/DiscussionContainer.tsx
  packages/components/src/DiscussionContainer/transformToStructuredComments.ts
  src/common/transformToUserComments.ts
  src/pages/Question/QuestionComments.tsx
  src/pages/Question/QuestionPage.tsx
Labels: Review allow-preview ✅

#3247 fix(components): remove margin from first tab
  packages/components/src/TabbedContent/TabbedContent.tsx
Labels: Design, Review allow-preview ✅

#3252 feat: add content statistics to questions
  src/pages/Question/QuestionPage.tsx
  src/pages/Question/question.routes.test.tsx
Labels: Review allow-preview ✅

#3274 chore: refactor Research
  src/pages/Research/Content/ResearchArticle.test.tsx
  src/pages/Research/Content/ResearchComments.tsx
  src/pages/Research/Content/ResearchUpdate.test.tsx
  src/pages/Research/Content/ResearchUpdate.tsx
Labels: Mod: Research 🔬

#3277 test: introduce junit output for component and (serverless) functions
  .circleci/config.yml
  functions/package.json
  packages/components/.gitignore
  packages/components/package.json
Labels: Backend

#3287 chore: refactor image input field
  src/common/Form/ImageInput.field.tsx
  src/common/Form/ImageInput/DeleteImage.tsx
  src/common/Form/ImageInput/ImageConverterList.tsx
  src/common/Form/ImageInput/ImageInput.tsx
  src/common/Form/ImageInput/ImageInputWrapper.tsx
  src/common/Form/ImageInput/getPresentFiles.ts
  src/common/Form/ImageInput/setSrc.ts
  src/common/Form/ImageInput/types.ts
Labels: Review allow-preview ✅

#3310 feat(notifications): add generic comment notification
  functions/src/emailNotifications/__snapshots__/createNotificationEmails.spec.ts.snap
  functions/src/emailNotifications/createNotificationEmails.spec.ts
  functions/src/emailNotifications/utils.ts
  functions/src/emulator/seed/content-generate.ts
  packages/components/src/NotificationItem/NotificationItem.stories.tsx
  packages/components/src/NotificationList/NotificationList.stories.tsx
  packages/cypress/src/integration/notifications.spec.ts
  shared/models/notifications.ts
  src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
  src/pages/common/Header/getFormattedNotifications.tsx
  src/stores/Howto/howto.store.test.ts
  src/stores/Howto/howto.store.tsx
  src/stores/Research/research.store.test.ts
  src/stores/Research/research.store.tsx
Labels: Backend, Mod: HowTo 📰, Review allow-preview ✅

#3288 Feat: sign-up message for contact form
  src/pages/User/contact/UserContactForm.test.tsx
  src/pages/User/contact/UserContactForm.tsx
  src/pages/User/contact/UserContactNotLoggedIn.tsx
  src/pages/User/contact/index.ts
  src/pages/User/content/SpaceProfile.tsx
  src/pages/User/content/UserContactAndLinks.tsx
Labels: Review allow-preview ✅, Onboarding experience

#3269 Feat: Add crop image component
  packages/components/package.json
  packages/components/src/ImageCrop/ImageCrop.stories.tsx
  packages/components/src/ImageCrop/ImageCrop.test.tsx
  packages/components/src/ImageCrop/ImageCrop.tsx
  packages/components/src/ImageCrop/canvasPreview.ts
  packages/components/src/ImageCrop/centerAspectCrop.ts
  packages/components/src/ImageCrop/useDebounceEffect.ts
  packages/components/src/Loader/Loader.stories.tsx
  packages/components/src/Loader/Loader.tsx
  packages/components/src/index.ts
  yarn.lock
Labels: Review allow-preview ✅
