Repository ONEARMY/community-platform, pull requests merged in 2024-04, with the labels that each got.

#3404 chore: update faker-js
  functions/src/emailNotifications/development/entry-server.mjs
  package.json
  src/stores/User/user.store.test.tsx
  src/test/factories/Comment.ts
  src/test/factories/Discussion.ts
  src/test/factories/Howto.ts
  src/test/factories/MapPin.ts
  src/test/factories/Notification.ts
  src/test/factories/Question.ts
  src/test/factories/ResearchItem.ts
  src/test/factories/User.ts
  yarn.lock
Labels: Backend

#3423 fix: revert "refactor user notification tests"
  functions/src/aggregations/common.aggregations.ts
  functions/src/aggregations/userNotifications.aggregations.spec.ts
  functions/src/aggregations/userNotifications.aggregations.ts
Labels: Backend

#3422 feat: support nested comments on Research comments
  packages/components/src/CreateComment/CreateComment.tsx
  packages/components/src/CreateReply/CreateReply.stories.tsx
  packages/components/src/CreateReply/CreateReply.test.tsx
  packages/components/src/CreateReply/CreateReply.tsx
  src/pages/Research/Content/ResearchComments.tsx
  src/stores/Research/research.store.test.ts
  src/stores/Research/research.store.tsx
Labels: Review allow-preview ✅, Mod: Research 🔬

#3430 fix: hide thumbnail for single image
  packages/components/src/ImageGallery/ImageGallery.stories.tsx
  packages/components/src/ImageGallery/ImageGallery.test.tsx
  packages/components/src/ImageGallery/ImageGallery.tsx
Labels: Review allow-preview ✅

#3370 feat: add support badge Username component
  packages/components/src/ArticleCallToAction/ArticleCallToAction.stories.tsx
  packages/components/src/ArticleCallToAction/ArticleCallToAction.tsx
  packages/components/src/CommentItem/CommentItem.tsx
  packages/components/src/CommentItem/types.ts
  packages/components/src/MapMemberCard/MapMemberCard.stories.tsx
  packages/components/src/MapMemberCard/MapMemberCard.tsx
  packages/components/src/UserStatistics/UserStatistics.tsx
  packages/components/src/Username/Username.stories.tsx
  packages/components/src/Username/Username.test.tsx
  packages/components/src/Username/Username.tsx
  packages/components/src/types/common.ts
  packages/components/src/utils.ts
  src/models/discussion.models.tsx
  src/pages/Howto/Content/Howto/Howto.tsx
  src/pages/Howto/Content/HowtoList/HowToCard.tsx
  src/pages/Maps/Content/MapView/Popup.tsx
  src/pages/Research/Content/ResearchDescription.tsx
  src/pages/Research/Content/ResearchListItem.tsx
  src/pages/Research/Content/ResearchUpdate.tsx
  src/pages/User/content/MemberProfile.tsx
  src/pages/User/content/SpaceProfile.tsx
  src/pages/common/UserNameTag/UserNameTag.tsx
  src/stores/Discussions/discussions.store.tsx
Labels: Backend, Mod: HowTo 📰, Mod: Maps 🗺, Review allow-preview ✅, Mod: Research 🔬, 🤝 Awaiting author

#3433 fix: replace AspectImage with Image and Boxes
  src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
Labels: Mod: HowTo 📰, Review allow-preview ✅, 🤝 Awaiting author

#3331 fix: Add spaces to notifications with urls
  src/pages/common/Header/getFormattedNotifications.tsx
Labels: 🤝 Awaiting author

#3438 Fix: un-revert "refactor user notification tests"
  functions/src/aggregations/common.aggregations.ts
  functions/src/aggregations/userNotifications.aggregations.spec.ts
  functions/src/aggregations/userNotifications.aggregations.ts
Labels: Backend

#3416 fix: profiles being wiped
  src/models/user.models.tsx
  src/pages/User/content/UserProfile.tsx
  src/stores/User/user.store.test.tsx
  src/stores/User/user.store.ts
Labels: Review allow-preview ✅

#3434 Refactor: increment counts
  src/pages/Howto/Content/Howto/Howto.test.tsx
  src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
  src/pages/Question/QuestionPage.tsx
  src/pages/Question/question.routes.test.tsx
  src/pages/Research/Content/ResearchArticle.test.tsx
  src/pages/Research/Content/ResearchDescription.tsx
  src/stores/Howto/howto.store.test.ts
  src/stores/Howto/howto.store.tsx
  src/stores/Question/question.store.test.tsx
  src/stores/Question/question.store.tsx
  src/stores/Research/research.store.test.ts
  src/stores/Research/research.store.tsx
  src/stores/RootStore.tsx
  src/stores/common/incrementDocViewCount.tsx
  src/utils/helpers.ts
  src/utils/incrementViewCount.test.ts
  src/utils/incrementViewCount.ts
Labels: Mod: HowTo 📰, Mod: Research 🔬

#3442 refactor: download counts
  packages/components/src/DownloadCounter/DownloadCounter.stories.tsx
  packages/components/src/DownloadCounter/DownloadCounter.test.tsx
  packages/components/src/DownloadCounter/DownloadCounter.tsx
  packages/components/src/index.ts
  packages/cypress/src/integration/howto/read.spec.ts
  packages/cypress/src/integration/research/read.spec.ts
  shared/mocks/data/howtos.ts
  shared/mocks/data/research.ts
  src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
  src/pages/Research/Content/ResearchUpdate.tsx
Labels: Mod: HowTo 📰, Mod: Research 🔬

#3441 fix: questions discussion actions updating display
  packages/components/src/CommentItem/CommentItem.tsx
  packages/components/src/EditComment/EditComment.tsx
  packages/cypress/src/integration/questions/read.spec.ts
  src/pages/Question/QuestionDiscussion.tsx
Labels: Review allow-preview ✅

#3444 Refactor: Slugs
  packages/cypress/src/integration/questions/write.spec.ts
  src/pages/Research/Content/Common/Research.form.tsx
  src/stores/Howto/howto.store.tsx
  src/stores/Question/question.store.test.tsx
  src/stores/Question/question.store.tsx
  src/stores/Research/research.store.tsx
  src/stores/common/__mocks__/module.store.ts
  src/stores/common/module.store.test.tsx
  src/stores/common/module.store.ts
Labels: Mod: Research 🔬

#3415 Refactor/research search
  firestore.indexes.json
  packages/components/src/UserStatistics/UserStatistics.test.tsx
  packages/components/src/UserStatistics/UserStatistics.tsx
  packages/cypress/src/integration/research/read.spec.ts
  packages/cypress/src/integration/research/write.spec.ts
  src/models/research.models.tsx
  src/pages/Question/constants.ts
  src/pages/Research/Content/ResearchComments.tsx
  src/pages/Research/Content/ResearchFilterHeader.tsx
  src/pages/Research/Content/ResearchList.tsx
  src/pages/Research/Content/ResearchListItem.tsx
  src/pages/Research/Content/ResearchUpdate.tsx
  src/pages/Research/ResearchSortOptions.ts
  src/pages/Research/constants.ts
  src/pages/Research/labels.ts
  src/pages/Research/research.routes.test.tsx
  src/pages/Research/research.service.test.ts
  src/pages/Research/research.service.ts
  src/stores/Research/research.store.test.ts
  src/stores/Research/research.store.tsx
  src/utils/helpers.ts
Labels: Mod: Research 🔬

#3428 fix: friendly sign up validation errors
  packages/cypress/src/integration/SignUp.spec.ts
  shared/messages.ts
  src/pages/SignUp/SignUp.tsx
Labels: 🤝 Awaiting author

#3457 chore: drop old research comments update
  functions/src/userUpdates/index.ts
Labels: Backend

#3447 Feat: Function to update discussions when user details change
  functions/src/models.ts
  functions/src/userUpdates/hasKeyDetailsChanged.test.ts
  functions/src/userUpdates/hasKeyDetailsChanged.ts
  functions/src/userUpdates/index.test.ts
  functions/src/userUpdates/index.ts
  functions/src/userUpdates/updateDiscussionComments.test.ts
  functions/src/userUpdates/updateDiscussionComments.ts
  shared/mocks/data/discussions.ts
  src/models/discussion.models.tsx
  src/stores/Discussions/discussion.store.test.ts
  src/stores/Discussions/discussions.store.tsx
  src/test/factories/Discussion.ts
Labels: Backend

#3466 feat: remove map streaming
  src/pages/Maps/Maps.tsx
  src/stores/Maps/maps.store.ts
  src/stores/databaseV2/types/index.d.ts
Labels: Mod: Maps 🗺
