Repository ONEARMY/community-platform, pull requests merged in 2024-12, with the labels that each got.

#4020 feat: Improve CreateComment and CreateReply components (ONEARMY#3656)…
  packages/components/src/CreateComment/CreateComment.css
  packages/components/src/CreateComment/CreateComment.test.tsx
  packages/components/src/CreateComment/CreateComment.tsx
Labels: Review allow-preview ✅

#4030 fix/profile-creation
  functions/src/supabaseSync/index.ts
Labels: Backend

#3996 feat: create API for questions search
  packages/cypress/src/integration/questions/search.spec.ts
  src/pages/Question/QuestionFilterHeader.tsx
  src/pages/Question/QuestionListing.tsx
  src/pages/Question/question.service.test.ts
  src/pages/Question/question.service.ts
  src/routes/api.questions.categories.ts
  src/routes/api.questions.ts
Labels: Review allow-preview ✅

#4042 feat: update ui of map badges on list view
  packages/components/package.json
  packages/components/src/CardButton/CardButton.tsx
  packages/components/src/Icon/Icon.tsx
  packages/components/src/MapFilterList/MapFilterList.stories.tsx
  packages/components/src/MapFilterProfileTypeCardList/MapFilterProfileTypeCardList.tsx
  packages/components/src/MemberTypeVerticalList/MemberTypeVerticalList.client.tsx
  packages/components/src/MemberTypeVerticalList/MemberTypeVerticalList.stories.tsx
  packages/components/src/MemberTypeVerticalList/MemberTypeVerticalList.test.tsx
  packages/components/src/VerticalList/Arrows.tsx
  packages/components/src/VerticalList/VerticalList.stories.tsx
  packages/components/src/VerticalList/VerticalList.tsx
  packages/components/src/index.ts
  packages/cypress/src/integration/map.spec.ts
  packages/themes/src/common/commonStyles.ts
  src/pages/Maps/Content/MapView/MapWithListHeader.tsx
  yarn.lock
Labels: Mod: Maps 🗺, Review allow-preview ✅

#4054 fix: rendering research updates on navigation
  src/pages/Research/Content/ResearchArticle.tsx
Labels: Mod: Research 🔬
