Repository ONEARMY/community-platform, pull requests merged in 2024-06, with the labels that each got.

#3587 feat(discussions): add avatars
  functions/src/userUpdates/hasKeyDetailsChanged.test.ts
  functions/src/userUpdates/hasKeyDetailsChanged.ts
  functions/src/userUpdates/updateDiscussionComments.test.ts
  functions/src/userUpdates/updateDiscussionComments.ts
  packages/components/src/CommentItem/CommentItem.stories.tsx
  packages/components/src/CommentItem/CommentItem.test.tsx
  packages/components/src/CommentItem/CommentItem.tsx
  packages/components/src/CommentItem/types.ts
  packages/components/src/CommentList/CommentList.stories.tsx
  packages/components/src/CommentList/CommentList.test.tsx
  packages/components/src/CommentList/CommentList.tsx
  packages/components/src/CreateComment/CreateComment.tsx
  packages/components/src/DiscussionContainer/DiscussionContainer.stories.tsx
  packages/components/src/DiscussionContainer/DiscussionContainer.tsx
  packages/components/src/DiscussionTitle/DiscussionTitle.tsx
  packages/components/src/utils.ts
  packages/cypress/src/integration/questions/discussions.spec.ts
  shared/mocks/data/discussions.ts
  src/common/DiscussionWrapper.tsx
  src/models/discussion.models.tsx
  src/models/user.models.tsx
  src/stores/Discussions/discussions.store.tsx
Labels: Backend, Review allow-preview ✅

#3621 fix: question form submitting not instantly set
  src/pages/Question/Content/Common/QuestionForm.tsx
  src/stores/Question/question.store.tsx
Labels: Review allow-preview ✅

#3644 fix: search by modified
  firestore.indexes.json
  src/pages/Howto/howto.service.ts
  src/pages/Research/Content/ResearchListItem.tsx
  src/pages/Research/research.service.ts
Labels: Mod: HowTo 📰, Review allow-preview ✅, Mod: Research 🔬

#3638 test(functions): improve testing of notification email content (#2795)
  functions/src/emailNotifications/createNotificationEmails.spec.ts
Labels: Backend

#3646 fix: research modified timestamp
  src/pages/Research/Content/ResearchListItem.tsx
Labels: Mod: Research 🔬

#3658 chore: update test router
  packages/components/.storybook/preview.tsx
  packages/components/src/test/utils.tsx
  src/pages/Howto/Content/Common/Howto.form.test.tsx
  src/pages/Howto/Howto.tsx
  src/pages/PageList.tsx
  src/pages/Research/Content/Common/ResearchUpdate.form.test.tsx
  src/pages/Research/research.routes.tsx
  src/pages/User/user.routes.test.tsx
  src/pages/User/user.routes.tsx
  src/pages/UserSettings/SettingsPage.tsx
  src/pages/UserSettings/UserSettings.test.tsx
  src/pages/common/Header/getFormattedNotifications.test.tsx
Labels: Mod: HowTo 📰, Mod: Research 🔬

#3648 feat: refactor send message to a cloud function
  functions/src/Utils/doc.utils.ts
  functions/src/index.ts
  functions/src/messages/messages.spec.ts
  functions/src/messages/messages.ts
  packages/cypress/src/integration/profile.spec.ts
  shared/models/index.ts
  shared/models/messages.ts
  src/pages/User/contact/UserContactFieldEmail.tsx
  src/pages/User/contact/UserContactForm.test.tsx
  src/pages/User/contact/UserContactForm.tsx
  src/pages/User/contact/index.ts
  src/services/message.service.ts
  src/stores/Message/message.store.test.ts
  src/stores/Message/message.store.tsx
  src/stores/RootStore.tsx
Labels: Backend

#3586 fix: display research draft updates for author and admins
  packages/components/src/Icon/svgs.tsx
  packages/cypress/src/integration/research/write.spec.ts
  src/pages/Research/Content/Common/ResearchUpdate.form.tsx
  src/pages/Research/Content/ResearchArticle.tsx
  src/pages/Research/Content/ResearchDescription.tsx
  src/pages/Research/Content/ResearchListItem.tsx
  src/pages/Research/researchHelpers.test.ts
  src/pages/Research/researchHelpers.ts
  src/utils/helpers.ts
Labels: Review allow-preview ✅, Mod: Research 🔬, 🤝 Awaiting author

#3619 Feat/add questions webhook
  functions/src/Integrations/firebase-discord.ts
  functions/src/Integrations/index.ts
Labels: Backend

#3665 chore: make format match other discord webhooks
  functions/src/Integrations/firebase-discord.ts
Labels: Backend

#3666 chore: improve emulator data
  functions/data/emulator/auth_export/accounts.json
  functions/data/emulator/firebase-export-metadata.json
  functions/data/emulator/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  functions/data/emulator/firestore_export/all_namespaces/all_kinds/output-0
  functions/data/emulator/firestore_export/firestore_export.overall_export_metadata
  functions/data/emulator/storage_export/blobs/0a41f511-5527-4fd0-b354-253ac23f10e4
  functions/data/emulator/storage_export/blobs/10c0603e-034a-4d30-a457-c4fa252d4035
  functions/data/emulator/storage_export/blobs/130874ce-85df-4050-be97-3a84ee5b521b
  functions/data/emulator/storage_export/blobs/19e0c820-3734-4f2c-848f-3b713eb06223
  functions/data/emulator/storage_export/blobs/1a4875c3-091d-492c-8070-e7c8aa537924
  functions/data/emulator/storage_export/blobs/35af263b-2759-4a1a-b683-7d684b11e460
  functions/data/emulator/storage_export/blobs/37e4038d-98a8-4d08-9d75-f61fc83578d2
  functions/data/emulator/storage_export/blobs/40aa4688-d649-4f74-add0-f3f0fae09a56
  functions/data/emulator/storage_export/blobs/41dfe6f5-44bd-4d7d-834d-a11666ebb6fd
  functions/data/emulator/storage_export/blobs/42c0173f-b23f-4b6e-abb5-83160bd2398d
  functions/data/emulator/storage_export/blobs/683ce1b8-8cd0-4cce-94cd-5a15d3e335c2
  functions/data/emulator/storage_export/blobs/6e5bf98a-518b-4fea-af93-66e5d1f3bd93
  functions/data/emulator/storage_export/blobs/7a92fa6a-091e-41b9-b313-8aa0598a3572
  functions/data/emulator/storage_export/blobs/7f478f81-52b9-465b-988d-f4be505d4d9a
  functions/data/emulator/storage_export/blobs/8366f2c6-4a85-4890-bd9a-74fce6a588b4
  functions/data/emulator/storage_export/blobs/c4800f56-9447-41b5-9a34-1a5d1c0f01f5
  functions/data/emulator/storage_export/blobs/f2f93677-58de-488d-97ca-1070b505309f
  functions/data/emulator/storage_export/blobs/ff704dc7-7343-4b8f-ba5a-b6d4eb8de3f2
  functions/data/emulator/storage_export/metadata/0a41f511-5527-4fd0-b354-253ac23f10e4.json
  functions/data/emulator/storage_export/metadata/10c0603e-034a-4d30-a457-c4fa252d4035.json
  functions/data/emulator/storage_export/metadata/130874ce-85df-4050-be97-3a84ee5b521b.json
  functions/data/emulator/storage_export/metadata/19e0c820-3734-4f2c-848f-3b713eb06223.json
  functions/data/emulator/storage_export/metadata/1a4875c3-091d-492c-8070-e7c8aa537924.json
  functions/data/emulator/storage_export/metadata/35af263b-2759-4a1a-b683-7d684b11e460.json
  functions/data/emulator/storage_export/metadata/37e4038d-98a8-4d08-9d75-f61fc83578d2.json
  functions/data/emulator/storage_export/metadata/40aa4688-d649-4f74-add0-f3f0fae09a56.json
  functions/data/emulator/storage_export/metadata/41dfe6f5-44bd-4d7d-834d-a11666ebb6fd.json
  functions/data/emulator/storage_export/metadata/42c0173f-b23f-4b6e-abb5-83160bd2398d.json
  functions/data/emulator/storage_export/metadata/683ce1b8-8cd0-4cce-94cd-5a15d3e335c2.json
  functions/data/emulator/storage_export/metadata/6e5bf98a-518b-4fea-af93-66e5d1f3bd93.json
  functions/data/emulator/storage_export/metadata/7a92fa6a-091e-41b9-b313-8aa0598a3572.json
  functions/data/emulator/storage_export/metadata/7f478f81-52b9-465b-988d-f4be505d4d9a.json
  functions/data/emulator/storage_export/metadata/8366f2c6-4a85-4890-bd9a-74fce6a588b4.json
  functions/data/emulator/storage_export/metadata/c4800f56-9447-41b5-9a34-1a5d1c0f01f5.json
  functions/data/emulator/storage_export/metadata/f2f93677-58de-488d-97ca-1070b505309f.json
  functions/data/emulator/storage_export/metadata/ff704dc7-7343-4b8f-ba5a-b6d4eb8de3f2.json
Labels: Backend

#3668 Fix/admin comments
  src/common/DiscussionWrapper.test.tsx
  src/common/transformToUserComments.ts
  src/pages/Howto/Content/Common/Howto.form.test.tsx
  src/pages/Question/question.routes.test.tsx
Labels: Mod: HowTo 📰

#3669 chore: clenaup unit tests
  functions/src/seo/sitemap/sitemap.test.ts
  packages/components/src/DiscussionContainer/DiscussionContainer.test.tsx
  packages/components/src/DonationRequest/DonationRequest.test.tsx
  packages/components/src/EditComment/EditComment.test.tsx
  packages/components/src/ImageGallery/ImageGallery.test.tsx
  packages/components/src/MapMemberCard/MapMemberCard.test.tsx
  packages/components/src/TabbedContent/TabbedContent.test.tsx
  src/common/DiscussionWrapper.test.tsx
  src/common/HideDiscussionContainer.test.tsx
  src/common/ScrollToTop.test.tsx
  src/pages/Howto/Content/Common/HowtoCategoryGuidance.test.tsx
  src/pages/Howto/Content/Common/HowtoErrors.test.tsx
  src/pages/Howto/Content/Howto/Howto.test.tsx
  src/pages/Howto/howto.service.test.ts
  src/pages/Maps/Maps.test.tsx
  src/pages/Question/QuestionPage.test.tsx
  src/pages/Question/question.routes.test.tsx
  src/pages/Question/question.service.test.ts
  src/pages/Research/Content/Common/ResearchErrors.test.tsx
  src/pages/Research/Content/Common/ResearchUpdate.form.test.tsx
  src/pages/Research/Content/ResearchArticle.test.tsx
  src/pages/Research/research.routes.test.tsx
  src/pages/Research/research.service.test.ts
  src/pages/Research/researchHelpers.test.ts
  src/pages/User/contact/UserContactForm.test.tsx
  src/pages/User/impact/Impact.test.tsx
  src/pages/User/impact/ImpactField.test.tsx
  src/pages/User/user.routes.test.tsx
  src/pages/UserSettings/UserSettings.test.tsx
  src/pages/UserSettings/content/formSections/Focus.section.test.tsx
  src/pages/UserSettings/content/formSections/PatreonIntegration.test.tsx
  src/pages/UserSettings/content/formSections/SettingsError.test.tsx
  src/stores/Discussions/discussion.store.test.ts
  src/stores/Question/question.store.test.tsx
  src/stores/Research/research.store.test.ts
  src/stores/User/notifications.store.test.tsx
Labels: Backend, Mod: HowTo 📰, Mod: Maps 🗺, Mod: Research 🔬

#3672 fix(research): change default sort to last updated
  src/pages/Research/Content/ResearchFilterHeader.tsx
  src/pages/Research/Content/ResearchList.tsx
Labels: Mod: Research 🔬

#3673 chore(functions): remove request dependency
  functions/package.json
  functions/src/Integrations/firebase-slack.ts
  yarn.lock
Labels: Backend

#3675 fix: the reply button UI
  packages/components/src/ButtonShowReplies/ButtonShowReplies.tsx
Labels: Review allow-preview ✅

#3657 chore: update React and dev dependencies
  .eslintrc.json
  functions/src/emailNotifications/__snapshots__/createNotificationEmails.spec.ts.snap
  functions/src/emailNotifications/createModerationEmails.spec.ts
  functions/src/emailNotifications/createNotificationEmails.spec.ts
  functions/src/emailNotifications/createSubmissionEmails.spec.ts
  functions/src/emailNotifications/templates.ts
  functions/src/emailNotifications/utils.ts
  functions/src/emulator/seed/data-clean.ts
  functions/src/seo/render/render.spec.ts
  package.json
  packages/components/package.json
  packages/components/src/BlockedRoute/BlockedRoute.stories.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/ResearchEditorOverview/ResearchEditorOverview.stories.tsx
  packages/components/src/ResearchEditorOverview/__snapshots__/ResearchEditorOverview.test.tsx.snap
  packages/components/src/UserStatistics/UserStatistics.stories.tsx
  packages/components/src/VideoPlayer/VideoPlayer.stories.tsx
  packages/cypress/package.json
  packages/cypress/src/integration/howto/write.spec.ts
  packages/cypress/src/integration/research/write.spec.ts
  packages/cypress/src/support/CustomAssertations.ts
  packages/cypress/src/support/commands.ts
  packages/cypress/src/support/db/firebase.ts
  packages/themes/src/types/index.ts
  shared/models/notifications.ts
  src/common/AuthWrapper.tsx
  src/common/DiscussionWrapper.test.tsx
  src/common/Form/ImageInput/ImageConverter.tsx
  src/common/Form/ImageInput/ImageConverterList.tsx
  src/common/Form/TagsSelect.field.tsx
  src/common/Tags/TagsSelect.tsx
  src/config/constants.ts
  src/index.tsx
  src/modules/profile/types.ts
  src/pages/Howto/Content/Common/Howto.form.test.tsx
  src/pages/Maps/Content/Controls/transformAvailableFiltersToGroups.tsx
  src/pages/Question/question.routes.test.tsx
  src/pages/Research/research.routes.test.tsx
  src/pages/Research/researchHelpers.ts
  src/pages/User/content/SpaceProfile.tsx
  src/pages/UserSettings/UserSettings.test.tsx
  src/pages/common/MainLayout/index.tsx
  src/stores/Howto/howto.store.tsx
  src/stores/Question/question.store.tsx
  src/stores/Research/research.store.tsx
  src/stores/common/module.store.ts
  src/stores/databaseV2/CollectionReference.ts
  src/stores/databaseV2/clients/FirestoreClient.ts
  src/utils/urlHelper.ts
  src/utils/validators.ts
  yarn.lock
Labels: Backend, Mod: HowTo 📰, Mod: Maps 🗺, Review allow-preview ✅, Mod: Research 🔬

#3680 feat: decrease margin top comment
  packages/components/src/CommentItem/CommentItem.tsx
Labels: Review allow-preview ✅

#3507 refactor(research): extract several components to simplify the form
  src/pages/Research/Content/Common/ResearchUpdate.form.tsx
  src/pages/Research/Content/CreateResearch/Form/DescriptionField.tsx
  src/pages/Research/Content/CreateResearch/Form/FilesFields.tsx
  src/pages/Research/Content/CreateResearch/Form/MediaFields.tsx
  src/pages/Research/Content/CreateResearch/Form/TitleField.tsx
Labels: Mod: Research 🔬, 🤝 Awaiting author

#3690 fix: spacing on profile
  packages/components/src/UserStatistics/UserStatistics.tsx
  src/pages/User/content/MemberProfile.tsx
Labels: Review allow-preview ✅

#3684 Add research update webhook
  functions/src/Integrations/firebase-discord.ts
  functions/src/Integrations/firebase-slack.ts
  functions/src/Integrations/index.ts
Labels: Backend, 🤝 Awaiting author

#3697 fix: rename templates.ts to templateHelpers.ts to avoid conflict with…
  functions/src/emailNotifications/createModerationEmails.spec.ts
  functions/src/emailNotifications/createModerationEmails.ts
  functions/src/emailNotifications/createNotificationEmails.ts
  functions/src/emailNotifications/createSubmissionEmails.spec.ts
  functions/src/emailNotifications/createSubmissionEmails.ts
  functions/src/emailNotifications/supporterBadgeEmails.ts
  functions/src/emailNotifications/templateHelpers.ts
  functions/src/emailNotifications/verifiedBadgeEmails.ts
Labels: Backend

#3705 chore: disable url preview
  functions/src/Integrations/firebase-discord.ts
Labels: Backend

#3704 chore: add healthcheck to backend emulator
  functions/emulator/Dockerfile
Labels: Backend

#3698 fix: run vitest tests sequentially
  package.json
  packages/components/vite.config.ts
  src/pages/Research/Content/ResearchArticle.test.tsx
  src/stores/Maps/filter.test.ts
  src/stores/Maps/filter.ts
  vite.config.ts
Labels: Mod: Research 🔬

#3707 fix: research test
  src/pages/Research/research.routes.test.tsx
Labels: Mod: Research 🔬

#3710 fix: send emails
  functions/src/emailNotifications/templates/index.ts
Labels: Backend

#3711 Chore/further emulator cleanup 3
  functions/emulator/Dockerfile
  packages/documentation/docs/Backend Development/firebase-emulator.md
Labels: Documentation, Backend

#3714 fix: research drafts
  src/pages/Research/Content/ResearchList.tsx
Labels: Mod: Research 🔬
