Repository ONEARMY/community-platform, pull requests merged in 2025-03, with the labels that each got.

#4119 feat: pages with comments more mobile friendly
  packages/components/src/Breadcrumbs/BreadcrumbsItem.tsx
  packages/components/src/CommentBody/CommentBody.tsx
  packages/components/src/CommentDisplay/CommentDisplay.tsx
  packages/components/src/CreateComment/CreateComment.tsx
  packages/components/src/DiscussionContainer/DiscussionContainer.tsx
  packages/themes/src/common/index.ts
  src/pages/Library/Content/List/LibraryCard.tsx
  src/pages/Library/Content/List/LibraryList.tsx
  src/pages/Library/Content/Page/Library.tsx
  src/pages/Library/Content/Page/LibraryDescription.tsx
  src/pages/Library/Content/Page/LibraryDiscussion.tsx
  src/pages/Library/Content/Page/LibraryStep.tsx
  src/pages/Question/QuestionListing.tsx
  src/pages/Question/QuestionPage.tsx
  src/pages/Research/Content/ResearchArticle.test.tsx
  src/pages/Research/Content/ResearchArticlePage.tsx
  src/pages/Research/Content/ResearchDescription.tsx
  src/pages/Research/Content/ResearchListItem.tsx
  src/pages/Research/Content/ResearchUpdate.tsx
  src/pages/common/Breadcrumbs/Breadcrumbs.tsx
  src/pages/common/CommentsSupabase/CommentItemSupabase.tsx
  src/pages/common/CommentsSupabase/CreateCommentSupabase.tsx
  src/pages/common/Layout/ListHeader.tsx
  src/pages/common/Layout/Main.tsx
  src/routes/_.research.$slug._index.tsx
Labels: Review allow-preview ✅, Mod: Research 🔬, Mod: Library 📰

#4148 chore: remove unused question functions
  functions/src/index.ts
  functions/src/questionUpdates/index.test.ts
  functions/src/questionUpdates/index.ts
Labels: Backend

#4124 feat: add new author badge
  packages/components/assets/images/author.svg
  packages/components/src/CommentAvatar/CommentAvatar.tsx
  packages/components/src/CommentDisplay/CommentDisplay.tsx
  packages/components/src/index.ts
  packages/components/src/providers/AuthorsContext.ts
  src/pages/Question/QuestionPage.tsx
  src/pages/common/CommentsSupabase/CommentSectionSupabase.tsx
Labels: Review allow-preview ✅

#4108 Drop MemberProfile component for SpaceProfile
  packages/cypress/src/integration/profile.spec.ts
  packages/cypress/src/integration/settings.spec.ts
  shared/mocks/data/users.ts
  src/pages/User/contact/UserContactForm.tsx
  src/pages/User/content/MemberProfile.tsx
  src/pages/User/content/ProfileContact.tsx
  src/pages/User/content/ProfileDetails.tsx
  src/pages/User/content/ProfileHeader.tsx
  src/pages/User/content/ProfileImage.tsx
  src/pages/User/content/ProfilePage.tsx
  src/pages/User/content/SpaceProfile.tsx
  src/pages/User/content/UserContactAndLinks.tsx
  src/pages/User/content/UserCreatedDocuments.tsx
  src/pages/User/content/UserProfile.tsx
  src/pages/User/impact/Impact.tsx
  src/routes/_.u.$id._index.tsx
Labels: Review allow-preview ✅

#4155 fix: flex for library steps
  src/pages/Library/Content/Page/LibraryStep.tsx
Labels: Mod: Library 📰

#4153 feat: migrate patreon to supabase
  .circleci/config.yml
  functions/src/Integrations/index.ts
  functions/src/Integrations/patreon.spec.ts
  functions/src/Integrations/patreon.ts
  packages/cypress/src/support/seedAccounts.ts
  shared/models/comment.ts
  shared/models/index.ts
  shared/models/patreonSettings.ts
  src/models/profile.model.ts
  src/models/question.model.ts
  src/pages/Patreon/Patreon.tsx
  src/pages/UserSettings/SettingsPageAccount.tsx
  src/pages/UserSettings/content/fields/PatreonIntegration.test.tsx
  src/pages/UserSettings/content/fields/PatreonIntegration.tsx
  src/routes/_.patreon.tsx
  src/routes/api.discussions.$sourceId.comments.ts
  src/routes/api.patreon.ts
  src/routes/api.questions.ts
  src/services/authService.server.ts
  src/services/patreonService.server.ts
  src/services/patreonService.ts
  src/services/questionService.server.ts
  src/stores/User/user.store.test.tsx
  src/stores/User/user.store.ts
  src/test/factories/Question.ts
  supabase/migrations/20250312063008_patreon.sql
Labels: Backend

#4144 refactor(functions): issue 4134 blocking user with incomplete profile…
  packages/cypress/src/integration/settings.spec.ts
  src/pages/UserSettings/SettingsPageMapPin.test.tsx
  src/pages/UserSettings/SettingsPageMapPin.tsx
  src/pages/UserSettings/labels.ts
Labels: Review allow-preview ✅

#4159 feat: block actions from incomplete profiles
  packages/cypress/src/integration/library/write.spec.ts
  packages/cypress/src/integration/questions/discussions.spec.ts
  packages/cypress/src/integration/questions/write.spec.ts
  packages/cypress/src/integration/research/write.spec.ts
  packages/cypress/src/integration/settings.spec.ts
  packages/cypress/src/support/commandsUi.ts
  packages/themes/src/common/button.ts
  src/common/UserAction.test.tsx
  src/common/UserAction.tsx
  src/pages/Library/Content/List/LibraryListHeader.tsx
  src/pages/Library/labels.ts
  src/pages/Question/QuestionListHeader.tsx
  src/pages/Question/labels.ts
  src/pages/Research/Content/CreateResearch/index.tsx
  src/pages/Research/Content/ResearchListHeader.tsx
  src/pages/Research/labels.ts
  src/pages/User/content/ProfileContact.tsx
  src/pages/UserSettings/SettingsPageUserProfile.tsx
  src/pages/common/CommentsSupabase/CreateCommentSupabase.tsx
  src/routes/_.library.create.tsx
  src/routes/_.questions.create.tsx
  src/routes/_.research.create.tsx
  src/stores/User/user.store.ts
Labels: Review allow-preview ✅, Mod: Research 🔬, Mod: Library 📰

#4174 refactor: sort out duplicate typing
  shared/models/author.ts
  shared/models/comment.ts
  shared/models/contentType.ts
  shared/models/image.ts
  shared/models/index.ts
  shared/models/notifications.ts
  shared/models/question.ts
  shared/models/tag.ts
  shared/models/tags.ts
  src/common/Tags/TagsSelectV2.tsx
  src/models/dbEndpoints.ts
  src/models/moderation.model.ts
  src/pages/Library/Content/Common/LibraryCategory.field.tsx
  src/pages/Library/Content/List/LibraryListHeader.tsx
  src/pages/Library/library.service.ts
  src/pages/Question/Content/Common/FormFields/QuestionCategory.field.tsx
  src/pages/Question/Content/Common/FormFields/QuestionImage.field.tsx
  src/pages/Question/Content/Common/QuestionForm.tsx
  src/pages/Question/QuestionEdit.tsx
  src/pages/Question/QuestionListItem.tsx
  src/pages/Question/QuestionListing.tsx
  src/pages/Question/QuestionPage.test.tsx
  src/pages/Question/QuestionPage.tsx
  src/pages/Question/question.service.ts
  src/pages/Research/Content/Common/ResearchCategorySelect.tsx
  src/pages/Research/research.service.ts
  src/pages/common/Breadcrumbs/Breadcrumbs.tsx
  src/pages/common/Category/CategoriesSelectV2.tsx
  src/routes/_.questions.$slug._index.tsx
  src/routes/_.questions.$slug.edit.tsx
  src/routes/api.discussions.$sourceId.comments.ts
  src/routes/api.mappins.$id.ts
  src/routes/api.mappins.ts
  src/routes/api.questions.$id.ts
  src/routes/api.questions.ts
  src/routes/api.research.categories.ts
  src/routes/api.research.drafts.count.ts
  src/routes/api.research.ts
  src/services/notificationsService.server.ts
  src/services/questionService.ts
  src/services/storageService.server.ts
  src/services/subscribersService.ts
  src/services/tagsService.ts
  src/services/usefulService.ts
  src/stores/Maps/maps.store.ts
  src/stores/common/module.store.ts
  src/stores/databaseV2/clients/DexieClient.ts
  src/stores/databaseV2/clients/FirestoreClient.ts
  src/stores/databaseV2/clients/RealtimeDatabaseClient.ts
  src/test/factories/Question.ts
  src/utils/comparisons.ts
  src/utils/formatImageListForGallery.ts
Labels: Mod: Research 🔬, Mod: Library 📰
